name: Agent CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'agent/**'
      - '.github/workflows/ci-agent.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'agent/**'

jobs:
  test-agent:
    name: Test Agent
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: ['1.21']
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: agent/go.sum

      - name: Install dependencies
        working-directory: agent
        run: go mod download

      - name: Run tests
        working-directory: agent
        run: go test -v ./...

      - name: Run go vet
        working-directory: agent
        run: go vet ./...

      - name: Build agent
        working-directory: agent
        run: go build -v ./cmd/ninjait-agent

      - name: Test agent executable
        working-directory: agent
        run: |
          chmod +x ninjait-agent || true
          ./ninjait-agent -version || ./ninjait-agent.exe -version

  build-release:
    name: Build Release Binaries
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build for all platforms
        working-directory: agent
        run: |
          make build-linux
          make build-windows
          make build-darwin

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: agent-binaries
          path: agent/build/*
          retention-days: 30

